version: "3"

services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./starwars:/app/starwars
      - ./startreck:/app/startreck
      - ./palpatine:/app/palpatine
      - ./apache/startreck.conf:/etc/apache2/sites-enabled/startreck.conf
        - ./apache/starwars.conf:/etc/apache2/sites-enabled/starwars.conf
