version: "3"

services:
  web:
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./starwars:/app/starwars
      - ./startreCk:/app/startreck
      - ./apache/startreck.conf:/etc/apache2/sites-enabled/startreck-.conf
        - ./apache/starwars.conf:/etc/apache2/sites-enabled/starwars-.conf
